#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#  date:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
#
#logging.level:
#  org.hibernate.SQL: debug