spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  date:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug

# s3
cloud:
  aws:
    s3:
      bucket: video-ex
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: AKIA4VMS2ZRBNN6BCCFB
      secret-key: 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

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://tempdb.cncmopyd0pfr.ap-northeast-2.rds.amazonaws.com:3306/speacher2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 19991021